name: publish to docker hub
on: [push, watch, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: fonoster/fonos-mediaserver
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          workdir: .
          tags: "latest,16.6.1,16.6,16"
